services:
  - name: carparking-backend
    type: web
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: "3000"
      - key: MONGO_URI
        value: "mongodb+srv://areckrodrigues1978:exSXYYzWsVMtqoMW@carparkingcluster.vx1k2.mongodb.net/?retryWrites=true&w=majority&appName=CarParkingCluster"
